# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='deshifr',
            new_name='label',
        ),
    ]
